### ISSUE TITLE
MetalLB speaker metrics endpoint not reachable

### ISSUE THREAD

**Issue by dcelasun** [christensenjairus/ClusterCreator#39]
Not sure what's wrong here 😕 
```sh
$ kubectl describe pods -n metallb-system metallb-speaker-tn4tt -o yaml
```
```yaml
# snip
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchFields:
              - key: metadata.name
                operator: In
                values:
                  - omega-controlplane-1
  containers:
    - args:
        - --port=7472
        - --log-level=info
      env:
        - name: METALLB_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: METALLB_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: METALLB_ML_BIND_ADDR
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: METALLB_ML_LABELS
          value: app.kubernetes.io/name=metallb,app.kubernetes.io/component=speaker
        - name: METALLB_ML_BIND_PORT
          value: "7946"
        - name: METALLB_ML_SECRET_KEY_PATH
          value: /etc/ml_secret_key
        - name: FRR_CONFIG_FILE
          value: /etc/frr_reloader/frr.conf
        - name: FRR_RELOADER_PID_FILE
          value: /etc/frr_reloader/reloader.pid
        - name: METALLB_BGP_TYPE
          value: frr
        - name: METALLB_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
      image: quay.io/metallb/speaker:v0.14.9
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /metrics
          port: monitoring
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: speaker
      ports:
        - containerPort: 7472
          hostPort: 7472
          name: monitoring
          protocol: TCP
        - containerPort: 7946
          hostPort: 7946
          name: memberlist-tcp
          protocol: TCP
        - containerPort: 7946
          hostPort: 7946
          name: memberlist-udp
          protocol: UDP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /metrics
          port: monitoring
          scheme: HTTP
        initialDelaySeconds: 10
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
# snip
```
So the speaker is definitely listening on 7472 and is, in fact, using `/metrics` as a readiness probe. But, when I try to proxy that port and curl `/metrics`, it fails:
```sh
$  kubectl port-forward -n metallb-system pods/metallb-speaker-tn4tt 7472:7472
Forwarding from 127.0.0.1:7472 -> 7472
Forwarding from [::1]:7472 -> 7472
Handling connection for 7472
E0307 23:07:34.887078  583457 portforward.go:424] "Unhandled Error" err="an error occurred forwarding 7472 -> 7472: error forwarding port 7472 to pod 393d9c6523618a9daaf64a4b83dc4cf6f24787906be14733fc2fe34b07bc0a50, uid : failed to execute portforward in network namespace \"host\": failed to connect to localhost:7472 inside namespace \"393d9c6523618a9daaf64a4b83dc4cf6f24787906be14733fc2fe34b07bc0a50\", IPv4: dial tcp4 127.0.0.1:7472: connect: connection refused IPv6 dial tcp6 [::1]:7472: connect: connection refused "
error: lost connection to pod
```
I'm not sure if this is a configuration issue about how metallb was initialized, but I'm very confused. Any ideas?
